var annotated_dup =
[
    [ "PurrNet", "namespacePurrNet.html", [
      [ "Authentication", "namespacePurrNet_1_1Authentication.html", [
        [ "AuthenticationBehaviour", "classPurrNet_1_1Authentication_1_1AuthenticationBehaviour.html", "classPurrNet_1_1Authentication_1_1AuthenticationBehaviour" ],
        [ "AuthenticationLayer", "classPurrNet_1_1Authentication_1_1AuthenticationLayer.html", null ],
        [ "AuthenticationRequest", "structPurrNet_1_1Authentication_1_1AuthenticationRequest.html", "structPurrNet_1_1Authentication_1_1AuthenticationRequest" ],
        [ "AuthenticationRequestData", "structPurrNet_1_1Authentication_1_1AuthenticationRequestData.html", "structPurrNet_1_1Authentication_1_1AuthenticationRequestData" ],
        [ "AuthenticationResponse", "structPurrNet_1_1Authentication_1_1AuthenticationResponse.html", "structPurrNet_1_1Authentication_1_1AuthenticationResponse" ],
        [ "SimpleAuthenticator", "classPurrNet_1_1Authentication_1_1SimpleAuthenticator.html", "classPurrNet_1_1Authentication_1_1SimpleAuthenticator" ]
      ] ],
      [ "Collections", "namespacePurrNet_1_1Collections.html", [
        [ "IReadonlyHashSet", "interfacePurrNet_1_1Collections_1_1IReadonlyHashSet.html", "interfacePurrNet_1_1Collections_1_1IReadonlyHashSet" ],
        [ "PurrHashSet", "classPurrNet_1_1Collections_1_1PurrHashSet.html", "classPurrNet_1_1Collections_1_1PurrHashSet" ]
      ] ],
      [ "Contributors", "namespacePurrNet_1_1Contributors.html", [
        [ "ContributorAttribute", "classPurrNet_1_1Contributors_1_1ContributorAttribute.html", null ],
        [ "CourtesyOfAttribute", "classPurrNet_1_1Contributors_1_1CourtesyOfAttribute.html", null ]
      ] ],
      [ "Logging", "namespacePurrNet_1_1Logging.html", [
        [ "LogStyle", "structPurrNet_1_1Logging_1_1LogStyle.html", null ]
      ] ],
      [ "Modules", "namespacePurrNet_1_1Modules.html", [
        [ "AckDeltaMessage", "structPurrNet_1_1Modules_1_1AckDeltaMessage.html", null ],
        [ "AuthModule", "classPurrNet_1_1Modules_1_1AuthModule.html", null ],
        [ "BroadcastModule", "classPurrNet_1_1Modules_1_1BroadcastModule.html", null ],
        [ "ChangeParentAction", "structPurrNet_1_1Modules_1_1ChangeParentAction.html", null ],
        [ "ChangeParentPacket", "structPurrNet_1_1Modules_1_1ChangeParentPacket.html", null ],
        [ "ColliderRollbackFactory", "classPurrNet_1_1Modules_1_1ColliderRollbackFactory.html", null ],
        [ "CookiesModule", "classPurrNet_1_1Modules_1_1CookiesModule.html", "classPurrNet_1_1Modules_1_1CookiesModule" ],
        [ "DeltaCache", "classPurrNet_1_1Modules_1_1DeltaCache.html", null ],
        [ "DeltaIDs", "classPurrNet_1_1Modules_1_1DeltaIDs.html", null ],
        [ "DeltaMessage", "structPurrNet_1_1Modules_1_1DeltaMessage.html", null ],
        [ "DeltaMessagesList", "structPurrNet_1_1Modules_1_1DeltaMessagesList.html", null ],
        [ "DeltaModule", "classPurrNet_1_1Modules_1_1DeltaModule.html", null ],
        [ "DeltaValue", "structPurrNet_1_1Modules_1_1DeltaValue.html", null ],
        [ "DespawnPacket", "structPurrNet_1_1Modules_1_1DespawnPacket.html", null ],
        [ "FinishSpawnPacket", "structPurrNet_1_1Modules_1_1FinishSpawnPacket.html", null ],
        [ "GameObjectFrameworkPiece", "structPurrNet_1_1Modules_1_1GameObjectFrameworkPiece.html", null ],
        [ "GameObjectPrototype", "structPurrNet_1_1Modules_1_1GameObjectPrototype.html", null ],
        [ "GameObjectRuntimePair", "structPurrNet_1_1Modules_1_1GameObjectRuntimePair.html", null ],
        [ "GlobalOwnershipModule", "classPurrNet_1_1Modules_1_1GlobalOwnershipModule.html", "classPurrNet_1_1Modules_1_1GlobalOwnershipModule" ],
        [ "HierarchyFactory", "classPurrNet_1_1Modules_1_1HierarchyFactory.html", null ],
        [ "HierarchyHistory", "classPurrNet_1_1Modules_1_1HierarchyHistory.html", null ],
        [ "HierarchyPool", "classPurrNet_1_1Modules_1_1HierarchyPool.html", "classPurrNet_1_1Modules_1_1HierarchyPool" ],
        [ "HierarchyV2", "classPurrNet_1_1Modules_1_1HierarchyV2.html", "classPurrNet_1_1Modules_1_1HierarchyV2" ],
        [ "IBroadcastCallback", "interfacePurrNet_1_1Modules_1_1IBroadcastCallback.html", null ],
        [ "INetworkModule", "interfacePurrNet_1_1Modules_1_1INetworkModule.html", null ],
        [ "IStableHashable", "interfacePurrNet_1_1Modules_1_1IStableHashable.html", null ],
        [ "LocalTransform", "structPurrNet_1_1Modules_1_1LocalTransform.html", null ],
        [ "NetworkTransformDelta", "structPurrNet_1_1Modules_1_1NetworkTransformDelta.html", null ],
        [ "NetworkTransformFactory", "classPurrNet_1_1Modules_1_1NetworkTransformFactory.html", null ],
        [ "NetworkTransformModule", "classPurrNet_1_1Modules_1_1NetworkTransformModule.html", null ],
        [ "PendingSceneOperation", "structPurrNet_1_1Modules_1_1PendingSceneOperation.html", null ],
        [ "PlayerJoinedEvent", "structPurrNet_1_1Modules_1_1PlayerJoinedEvent.html", null ],
        [ "PlayerLeftEvent", "structPurrNet_1_1Modules_1_1PlayerLeftEvent.html", null ],
        [ "PlayersManager", "classPurrNet_1_1Modules_1_1PlayersManager.html", "classPurrNet_1_1Modules_1_1PlayersManager" ],
        [ "PlayerSnapshotEvent", "structPurrNet_1_1Modules_1_1PlayerSnapshotEvent.html", null ],
        [ "PoolPair", "structPurrNet_1_1Modules_1_1PoolPair.html", null ],
        [ "PrefabPieceID", "structPurrNet_1_1Modules_1_1PrefabPieceID.html", null ],
        [ "PurrSceneSettings", "structPurrNet_1_1Modules_1_1PurrSceneSettings.html", null ],
        [ "RollbackModule", "classPurrNet_1_1Modules_1_1RollbackModule.html", null ],
        [ "RPCModule", "classPurrNet_1_1Modules_1_1RPCModule.html", null ],
        [ "RpcRequest", "structPurrNet_1_1Modules_1_1RpcRequest.html", null ],
        [ "RpcRequestResponseModule", "classPurrNet_1_1Modules_1_1RpcRequestResponseModule.html", null ],
        [ "RpcResponse", "structPurrNet_1_1Modules_1_1RpcResponse.html", null ],
        [ "ScenePlayersModule", "classPurrNet_1_1Modules_1_1ScenePlayersModule.html", "classPurrNet_1_1Modules_1_1ScenePlayersModule" ],
        [ "SceneScopedFactory", "classPurrNet_1_1Modules_1_1SceneScopedFactory.html", null ],
        [ "ScenesModule", "classPurrNet_1_1Modules_1_1ScenesModule.html", "classPurrNet_1_1Modules_1_1ScenesModule" ],
        [ "SceneState", "structPurrNet_1_1Modules_1_1SceneState.html", "structPurrNet_1_1Modules_1_1SceneState" ],
        [ "ServerLoginResponse", "structPurrNet_1_1Modules_1_1ServerLoginResponse.html", null ],
        [ "SimpleHistory", "classPurrNet_1_1Modules_1_1SimpleHistory.html", "classPurrNet_1_1Modules_1_1SimpleHistory" ],
        [ "SpawnID", "structPurrNet_1_1Modules_1_1SpawnID.html", null ],
        [ "SpawnPacket", "structPurrNet_1_1Modules_1_1SpawnPacket.html", "structPurrNet_1_1Modules_1_1SpawnPacket" ],
        [ "SpawnPacketBatch", "structPurrNet_1_1Modules_1_1SpawnPacketBatch.html", null ],
        [ "TickManager", "classPurrNet_1_1Modules_1_1TickManager.html", "classPurrNet_1_1Modules_1_1TickManager" ],
        [ "TransformIdentityPair", "structPurrNet_1_1Modules_1_1TransformIdentityPair.html", null ],
        [ "TransformInfo", "structPurrNet_1_1Modules_1_1TransformInfo.html", null ],
        [ "UsedByILAttribute", "classPurrNet_1_1Modules_1_1UsedByILAttribute.html", null ]
      ] ],
      [ "Packing", "namespacePurrNet_1_1Packing.html", [
        [ "BitPacker", "classPurrNet_1_1Packing_1_1BitPacker.html", "classPurrNet_1_1Packing_1_1BitPacker" ],
        [ "BitPackerPool", "classPurrNet_1_1Packing_1_1BitPackerPool.html", null ],
        [ "BitPackerWithLength", "structPurrNet_1_1Packing_1_1BitPackerWithLength.html", null ],
        [ "BitPackerWrapper", "structPurrNet_1_1Packing_1_1BitPackerWrapper.html", null ],
        [ "CompressedFloat", "structPurrNet_1_1Packing_1_1CompressedFloat.html", null ],
        [ "CompressedVector2", "structPurrNet_1_1Packing_1_1CompressedVector2.html", null ],
        [ "CompressedVector3", "structPurrNet_1_1Packing_1_1CompressedVector3.html", null ],
        [ "DeltaWritingScope", "structPurrNet_1_1Packing_1_1DeltaWritingScope.html", null ],
        [ "DiffOp", "structPurrNet_1_1Packing_1_1DiffOp.html", null ],
        [ "GeneratedByILAttribute", "classPurrNet_1_1Packing_1_1GeneratedByILAttribute.html", null ],
        [ "Half", "structPurrNet_1_1Packing_1_1Half.html", "structPurrNet_1_1Packing_1_1Half" ],
        [ "HalfVector2", "structPurrNet_1_1Packing_1_1HalfVector2.html", null ],
        [ "HalfVector3", "structPurrNet_1_1Packing_1_1HalfVector3.html", null ],
        [ "HalfVector4", "structPurrNet_1_1Packing_1_1HalfVector4.html", null ],
        [ "IPacked", "interfacePurrNet_1_1Packing_1_1IPacked.html", null ],
        [ "IPackedAuto", "interfacePurrNet_1_1Packing_1_1IPackedAuto.html", null ],
        [ "IPackedSimple", "interfacePurrNet_1_1Packing_1_1IPackedSimple.html", null ],
        [ "IStandaloneSerializable", "interfacePurrNet_1_1Packing_1_1IStandaloneSerializable.html", null ],
        [ "NetworkRegister", "classPurrNet_1_1Packing_1_1NetworkRegister.html", null ],
        [ "NormalizedFloat", "structPurrNet_1_1Packing_1_1NormalizedFloat.html", null ],
        [ "PackedByte", "structPurrNet_1_1Packing_1_1PackedByte.html", null ],
        [ "PackedInt", "structPurrNet_1_1Packing_1_1PackedInt.html", null ],
        [ "PackedLong", "structPurrNet_1_1Packing_1_1PackedLong.html", null ],
        [ "PackedQuaternion", "structPurrNet_1_1Packing_1_1PackedQuaternion.html", null ],
        [ "PackedSByte", "structPurrNet_1_1Packing_1_1PackedSByte.html", null ],
        [ "PackedShort", "structPurrNet_1_1Packing_1_1PackedShort.html", null ],
        [ "PackedUInt", "structPurrNet_1_1Packing_1_1PackedUInt.html", null ],
        [ "PackedULong", "structPurrNet_1_1Packing_1_1PackedULong.html", null ],
        [ "PackedUShort", "structPurrNet_1_1Packing_1_1PackedUShort.html", null ],
        [ "RegisterPackersAttribute", "classPurrNet_1_1Packing_1_1RegisterPackersAttribute.html", "classPurrNet_1_1Packing_1_1RegisterPackersAttribute" ],
        [ "Size", "structPurrNet_1_1Packing_1_1Size.html", null ]
      ] ],
      [ "Pooling", "namespacePurrNet_1_1Pooling.html", [
        [ "AllocationDetails", "structPurrNet_1_1Pooling_1_1AllocationDetails.html", null ],
        [ "CollectionPool", "classPurrNet_1_1Pooling_1_1CollectionPool.html", null ],
        [ "DictionaryPool", "classPurrNet_1_1Pooling_1_1DictionaryPool.html", null ],
        [ "DisposableArray", "structPurrNet_1_1Pooling_1_1DisposableArray.html", null ],
        [ "DisposableDictionary", "structPurrNet_1_1Pooling_1_1DisposableDictionary.html", null ],
        [ "DisposableHashSet", "structPurrNet_1_1Pooling_1_1DisposableHashSet.html", null ],
        [ "DisposableList", "structPurrNet_1_1Pooling_1_1DisposableList.html", null ],
        [ "GenericPool", "classPurrNet_1_1Pooling_1_1GenericPool.html", null ],
        [ "HashSetPool", "classPurrNet_1_1Pooling_1_1HashSetPool.html", null ],
        [ "ListPool", "classPurrNet_1_1Pooling_1_1ListPool.html", null ],
        [ "QueuePool", "classPurrNet_1_1Pooling_1_1QueuePool.html", null ],
        [ "StackPool", "classPurrNet_1_1Pooling_1_1StackPool.html", null ]
      ] ],
      [ "Profiler", "namespacePurrNet_1_1Profiler.html", [
        [ "BroadcastSample", "structPurrNet_1_1Profiler_1_1BroadcastSample.html", null ],
        [ "RpcsSample", "structPurrNet_1_1Profiler_1_1RpcsSample.html", null ],
        [ "TickSample", "classPurrNet_1_1Profiler_1_1TickSample.html", null ]
      ] ],
      [ "StateMachine", "namespacePurrNet_1_1StateMachine.html", [
        [ "IStateCommand", "interfacePurrNet_1_1StateMachine_1_1IStateCommand.html", null ],
        [ "StateMachine", "classPurrNet_1_1StateMachine_1_1StateMachine.html", "classPurrNet_1_1StateMachine_1_1StateMachine" ],
        [ "StateMachineState", "structPurrNet_1_1StateMachine_1_1StateMachineState.html", null ],
        [ "StateNode", "classPurrNet_1_1StateMachine_1_1StateNode.html", "classPurrNet_1_1StateMachine_1_1StateNode" ]
      ] ],
      [ "Transports", "namespacePurrNet_1_1Transports.html", [
        [ "ByteData", "structPurrNet_1_1Transports_1_1ByteData.html", null ],
        [ "ClientJoinInfo", "structPurrNet_1_1Transports_1_1ClientJoinInfo.html", null ],
        [ "CompositeTransport", "classPurrNet_1_1Transports_1_1CompositeTransport.html", null ],
        [ "Connection", "structPurrNet_1_1Transports_1_1Connection.html", null ],
        [ "GenericTransport", "classPurrNet_1_1Transports_1_1GenericTransport.html", "classPurrNet_1_1Transports_1_1GenericTransport" ],
        [ "HostJoinInfo", "structPurrNet_1_1Transports_1_1HostJoinInfo.html", null ],
        [ "IConnectable", "interfacePurrNet_1_1Transports_1_1IConnectable.html", null ],
        [ "IListener", "interfacePurrNet_1_1Transports_1_1IListener.html", null ],
        [ "ITransport", "interfacePurrNet_1_1Transports_1_1ITransport.html", null ],
        [ "LocalTransport", "classPurrNet_1_1Transports_1_1LocalTransport.html", null ],
        [ "PeerInfo", "classPurrNet_1_1Transports_1_1PeerInfo.html", null ],
        [ "PurrTransport", "classPurrNet_1_1Transports_1_1PurrTransport.html", null ],
        [ "Relayers", "structPurrNet_1_1Transports_1_1Relayers.html", null ],
        [ "RelayServer", "structPurrNet_1_1Transports_1_1RelayServer.html", null ],
        [ "UDPTransport", "classPurrNet_1_1Transports_1_1UDPTransport.html", "classPurrNet_1_1Transports_1_1UDPTransport" ],
        [ "WebTransport", "classPurrNet_1_1Transports_1_1WebTransport.html", null ]
      ] ],
      [ "Utils", "namespacePurrNet_1_1Utils.html", [
        [ "PurrDocsAttribute", "classPurrNet_1_1Utils_1_1PurrDocsAttribute.html", null ],
        [ "PurrLockAttribute", "classPurrNet_1_1Utils_1_1PurrLockAttribute.html", null ],
        [ "PurrReadOnlyAttribute", "classPurrNet_1_1Utils_1_1PurrReadOnlyAttribute.html", null ]
      ] ],
      [ "AlwaysVisibleRule", "classPurrNet_1_1AlwaysVisibleRule.html", "classPurrNet_1_1AlwaysVisibleRule" ],
      [ "BandwidthProfilerToFile", "classPurrNet_1_1BandwidthProfilerToFile.html", null ],
      [ "BoneInfo", "structPurrNet_1_1BoneInfo.html", null ],
      [ "BypassLoggingException", "classPurrNet_1_1BypassLoggingException.html", null ],
      [ "ChildRPCPacket", "structPurrNet_1_1ChildRPCPacket.html", null ],
      [ "ClientAttribute", "classPurrNet_1_1ClientAttribute.html", null ],
      [ "ColliderRollback", "classPurrNet_1_1ColliderRollback.html", null ],
      [ "DistanceRule", "classPurrNet_1_1DistanceRule.html", "classPurrNet_1_1DistanceRule" ],
      [ "DontDeltaCompressAttribute", "classPurrNet_1_1DontDeltaCompressAttribute.html", null ],
      [ "DontPackAttribute", "classPurrNet_1_1DontPackAttribute.html", null ],
      [ "GenericRPCHeader", "structPurrNet_1_1GenericRPCHeader.html", null ],
      [ "GuardFailureActionAttribute", "classPurrNet_1_1GuardFailureActionAttribute.html", null ],
      [ "HalfQuaternion", "structPurrNet_1_1HalfQuaternion.html", null ],
      [ "IMath", "interfacePurrNet_1_1IMath.html", null ],
      [ "INetworkManager", "interfacePurrNet_1_1INetworkManager.html", null ],
      [ "INetworkVisibilityRule", "interfacePurrNet_1_1INetworkVisibilityRule.html", "interfacePurrNet_1_1INetworkVisibilityRule" ],
      [ "Interpolated", "classPurrNet_1_1Interpolated.html", null ],
      [ "IOwnerAuth", "interfacePurrNet_1_1IOwnerAuth.html", null ],
      [ "IPlayerAuthenticator", "interfacePurrNet_1_1IPlayerAuthenticator.html", null ],
      [ "IPlayerBroadcaster", "interfacePurrNet_1_1IPlayerBroadcaster.html", null ],
      [ "IPlayerEvents", "interfacePurrNet_1_1IPlayerEvents.html", null ],
      [ "IPrefabProvider", "interfacePurrNet_1_1IPrefabProvider.html", null ],
      [ "IProvidePrefabInstantiated", "interfacePurrNet_1_1IProvidePrefabInstantiated.html", null ],
      [ "IProvideSpawnPoints", "interfacePurrNet_1_1IProvideSpawnPoints.html", null ],
      [ "IPurrEvents", "interfacePurrNet_1_1IPurrEvents.html", null ],
      [ "IRegisterModules", "interfacePurrNet_1_1IRegisterModules.html", null ],
      [ "IRpc", "interfacePurrNet_1_1IRpc.html", null ],
      [ "IServerSceneEvents", "interfacePurrNet_1_1IServerSceneEvents.html", null ],
      [ "ITick", "interfacePurrNet_1_1ITick.html", "interfacePurrNet_1_1ITick" ],
      [ "LocalModeAttribute", "classPurrNet_1_1LocalModeAttribute.html", null ],
      [ "MiscRules", "structPurrNet_1_1MiscRules.html", null ],
      [ "ModulesCollection", "structPurrNet_1_1ModulesCollection.html", null ],
      [ "NetworkAnimator", "classPurrNet_1_1NetworkAnimator.html", null ],
      [ "NetworkAssets", "classPurrNet_1_1NetworkAssets.html", "classPurrNet_1_1NetworkAssets" ],
      [ "NetworkBehaviour", "classPurrNet_1_1NetworkBehaviour.html", null ],
      [ "NetworkBoneID", "structPurrNet_1_1NetworkBoneID.html", null ],
      [ "NetworkBones", "classPurrNet_1_1NetworkBones.html", "classPurrNet_1_1NetworkBones" ],
      [ "NetworkID", "structPurrNet_1_1NetworkID.html", null ],
      [ "NetworkIdentity", "classPurrNet_1_1NetworkIdentity.html", "classPurrNet_1_1NetworkIdentity" ],
      [ "NetworkIdentityRules", "structPurrNet_1_1NetworkIdentityRules.html", null ],
      [ "NetworkManager", "classPurrNet_1_1NetworkManager.html", "classPurrNet_1_1NetworkManager" ],
      [ "NetworkModule", "classPurrNet_1_1NetworkModule.html", "classPurrNet_1_1NetworkModule" ],
      [ "NetworkOwnershipDebug", "classPurrNet_1_1NetworkOwnershipDebug.html", null ],
      [ "NetworkOwnershipToggle", "classPurrNet_1_1NetworkOwnershipToggle.html", "classPurrNet_1_1NetworkOwnershipToggle" ],
      [ "NetworkPrefabs", "classPurrNet_1_1NetworkPrefabs.html", "classPurrNet_1_1NetworkPrefabs" ],
      [ "NetworkReflection", "classPurrNet_1_1NetworkReflection.html", "classPurrNet_1_1NetworkReflection" ],
      [ "NetworkRules", "classPurrNet_1_1NetworkRules.html", null ],
      [ "NetworkSceneRules", "structPurrNet_1_1NetworkSceneRules.html", null ],
      [ "NetworkServerToggle", "classPurrNet_1_1NetworkServerToggle.html", "classPurrNet_1_1NetworkServerToggle" ],
      [ "NetworkTransform", "classPurrNet_1_1NetworkTransform.html", "classPurrNet_1_1NetworkTransform" ],
      [ "NetworkTransformData", "structPurrNet_1_1NetworkTransformData.html", null ],
      [ "NetworkTransformRules", "structPurrNet_1_1NetworkTransformRules.html", null ],
      [ "NetworkVisibilityRule", "classPurrNet_1_1NetworkVisibilityRule.html", "classPurrNet_1_1NetworkVisibilityRule" ],
      [ "NetworkVisibilityRuleSet", "classPurrNet_1_1NetworkVisibilityRuleSet.html", null ],
      [ "NoVisibilityRule", "classPurrNet_1_1NoVisibilityRule.html", "classPurrNet_1_1NoVisibilityRule" ],
      [ "ObserversRpcAttribute", "classPurrNet_1_1ObserversRpcAttribute.html", null ],
      [ "OwnerAttribute", "classPurrNet_1_1OwnerAttribute.html", null ],
      [ "OwnershipComponentToggle", "structPurrNet_1_1OwnershipComponentToggle.html", null ],
      [ "OwnershipGameObjectToggle", "structPurrNet_1_1OwnershipGameObjectToggle.html", null ],
      [ "OwnershipRules", "structPurrNet_1_1OwnershipRules.html", null ],
      [ "PlayerID", "structPurrNet_1_1PlayerID.html", null ],
      [ "PlayerIdentity", "classPurrNet_1_1PlayerIdentity.html", "classPurrNet_1_1PlayerIdentity" ],
      [ "PlayersBroadcaster", "classPurrNet_1_1PlayersBroadcaster.html", null ],
      [ "PlayerSpawner", "classPurrNet_1_1PlayerSpawner.html", "classPurrNet_1_1PlayerSpawner" ],
      [ "PrefabData", "structPurrNet_1_1PrefabData.html", null ],
      [ "PrefabLink", "classPurrNet_1_1PrefabLink.html", null ],
      [ "PrefabProviderScriptable", "classPurrNet_1_1PrefabProviderScriptable.html", null ],
      [ "PurrButtonAttribute", "classPurrNet_1_1PurrButtonAttribute.html", null ],
      [ "PurrContextButtonAttribute", "classPurrNet_1_1PurrContextButtonAttribute.html", null ],
      [ "PurrMonoBehaviour", "classPurrNet_1_1PurrMonoBehaviour.html", null ],
      [ "PurrSceneAttribute", "classPurrNet_1_1PurrSceneAttribute.html", null ],
      [ "PurrSceneInfo", "classPurrNet_1_1PurrSceneInfo.html", null ],
      [ "QuaternionWithParent", "structPurrNet_1_1QuaternionWithParent.html", null ],
      [ "RawNetManager", "classPurrNet_1_1RawNetManager.html", "classPurrNet_1_1RawNetManager" ],
      [ "Reference", "classPurrNet_1_1Reference.html", "classPurrNet_1_1Reference" ],
      [ "ReflectionData", "structPurrNet_1_1ReflectionData.html", null ],
      [ "RegisterNetworkTypeAttribute", "classPurrNet_1_1RegisterNetworkTypeAttribute.html", null ],
      [ "ReliableDeltaStream", "classPurrNet_1_1ReliableDeltaStream.html", "classPurrNet_1_1ReliableDeltaStream" ],
      [ "RPCInfo", "structPurrNet_1_1RPCInfo.html", null ],
      [ "RPCPacket", "structPurrNet_1_1RPCPacket.html", null ],
      [ "RpcRules", "structPurrNet_1_1RpcRules.html", null ],
      [ "RPCSignature", "structPurrNet_1_1RPCSignature.html", null ],
      [ "SaveHasherInFile", "classPurrNet_1_1SaveHasherInFile.html", null ],
      [ "ScaleWithParent", "structPurrNet_1_1ScaleWithParent.html", null ],
      [ "SceneID", "structPurrNet_1_1SceneID.html", null ],
      [ "SerializableDictionary", "classPurrNet_1_1SerializableDictionary.html", null ],
      [ "SerializableQueue", "classPurrNet_1_1SerializableQueue.html", null ],
      [ "SerializableSyncUnityEvent", "classPurrNet_1_1SerializableSyncUnityEvent.html", null ],
      [ "ServerAttribute", "classPurrNet_1_1ServerAttribute.html", null ],
      [ "ServerOnlyAttribute", "classPurrNet_1_1ServerOnlyAttribute.html", null ],
      [ "ServerRpcAttribute", "classPurrNet_1_1ServerRpcAttribute.html", null ],
      [ "SpawnPoint", "structPurrNet_1_1SpawnPoint.html", null ],
      [ "SpawnRules", "structPurrNet_1_1SpawnRules.html", null ],
      [ "StaticRPCPacket", "structPurrNet_1_1StaticRPCPacket.html", null ],
      [ "StatisticsManager", "classPurrNet_1_1StatisticsManager.html", "classPurrNet_1_1StatisticsManager" ],
      [ "StringUTF8", "structPurrNet_1_1StringUTF8.html", null ],
      [ "SyncArray", "classPurrNet_1_1SyncArray.html", "classPurrNet_1_1SyncArray" ],
      [ "SyncArrayChange", "structPurrNet_1_1SyncArrayChange.html", null ],
      [ "SyncDictionary", "classPurrNet_1_1SyncDictionary.html", "classPurrNet_1_1SyncDictionary" ],
      [ "SyncDictionaryChange", "structPurrNet_1_1SyncDictionaryChange.html", null ],
      [ "SyncEvent", "classPurrNet_1_1SyncEvent.html", "classPurrNet_1_1SyncEvent" ],
      [ "SyncEventBase", "classPurrNet_1_1SyncEventBase.html", "classPurrNet_1_1SyncEventBase" ],
      [ "SyncHashSet", "classPurrNet_1_1SyncHashSet.html", "classPurrNet_1_1SyncHashSet" ],
      [ "SyncHashSetChange", "structPurrNet_1_1SyncHashSetChange.html", null ],
      [ "SyncInput", "classPurrNet_1_1SyncInput.html", "classPurrNet_1_1SyncInput" ],
      [ "SyncList", "classPurrNet_1_1SyncList.html", "classPurrNet_1_1SyncList" ],
      [ "SyncListChange", "structPurrNet_1_1SyncListChange.html", null ],
      [ "SyncQueue", "classPurrNet_1_1SyncQueue.html", "classPurrNet_1_1SyncQueue" ],
      [ "SyncQueueChange", "structPurrNet_1_1SyncQueueChange.html", null ],
      [ "SyncTimer", "classPurrNet_1_1SyncTimer.html", "classPurrNet_1_1SyncTimer" ],
      [ "SyncVar", "classPurrNet_1_1SyncVar.html", "classPurrNet_1_1SyncVar" ],
      [ "TargetRpcAttribute", "classPurrNet_1_1TargetRpcAttribute.html", null ],
      [ "UnityLatestUpdate", "classPurrNet_1_1UnityLatestUpdate.html", null ],
      [ "Vector3WithParent", "structPurrNet_1_1Vector3WithParent.html", null ],
      [ "VisibilityRules", "structPurrNet_1_1VisibilityRules.html", null ]
    ] ]
];